spring:
  application:
    name: Dine-In-Order  # Added a space after "name:"

  # DataSource configuration
  datasource:
    url: jdbc:mysql://localhost:3306/Dine_In_Order?createDatabaseIfNotExist=true  # Added a space after "url:"
    username: root
    password: 9916Vish@

  jpa:
    show-sql: true  # Added a space after "show-sql:"
    hibernate:
      ddl-auto: update  # Added a space after "ddl-auto:"